/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers'
import { Provider, TransactionRequest } from '@ethersproject/providers'
import type {
  ExchangePoolAccessControl,
  ExchangePoolAccessControlInterface,
} from '../ExchangePoolAccessControl'

const _abi = [
  {
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'LIQUIDITY_PROVIDER_ROLE',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'role_',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'to_',
        type: 'address',
      },
    ],
    name: 'grantRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'role_',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'who_',
        type: 'address',
      },
    ],
    name: 'hasRole',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'role_',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'from_',
        type: 'address',
      },
    ],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]

const _bytecode =
  '0x608060405234801561001057600080fd5b50610374806100206000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c806320037cdd1461005c5780632f2ff15d1461009657806391d14854146100ab578063a217fddf146100ce578063d547741f146100d6575b600080fd5b6100837f42802a37d17e698ec3d88f7a6917f1f5a6abb4d99a8f4255c389e56d10218a6481565b6040519081526020015b60405180910390f35b6100a96100a4366004610302565b6100e9565b005b6100be6100b9366004610302565b610155565b604051901515815260200161008d565b610083600081565b6100a96100e4366004610302565b61017e565b60006100f58133610155565b6101465760405162461bcd60e51b815260206004820152601a60248201527f4164647265737320646f6573206e6f74206861766520726f6c6500000000000060448201526064015b60405180910390fd5b61015083836101e0565b505050565b6000918252602082815260408084206001600160a01b0393909316845291905290205460ff1690565b600061018a8133610155565b6101d65760405162461bcd60e51b815260206004820152601a60248201527f4164647265737320646f6573206e6f74206861766520726f6c65000000000000604482015260640161013d565b6101508383610272565b6000828152602081815260408083206001600160a01b038516845290915290205460ff16156102445760405162461bcd60e51b815260206004820152601060248201526f416c65726164792068617320726f6c6560801b604482015260640161013d565b6000918252602082815260408084206001600160a01b0390931684529190529020805460ff19166001179055565b6000828152602081815260408083206001600160a01b038516845290915290205460ff166102d75760405162461bcd60e51b8152602060048201526012602482015271446f6573206e6f74206861766520726f6c6560701b604482015260640161013d565b6000918252602082815260408084206001600160a01b0390931684529190529020805460ff19169055565b6000806040838503121561031557600080fd5b8235915060208301356001600160a01b038116811461033357600080fd5b80915050925092905056fea2646970667358221220fe4f4b644acdf70a4032b6503c4cf5646ae805f2cb9191d68d09c368bbce48da64736f6c63430008120033'

export class ExchangePoolAccessControl__factory extends ContractFactory {
  constructor(...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0])
    } else {
      super(...args)
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ExchangePoolAccessControl> {
    return super.deploy(overrides || {}) as Promise<ExchangePoolAccessControl>
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {})
  }
  attach(address: string): ExchangePoolAccessControl {
    return super.attach(address) as ExchangePoolAccessControl
  }
  connect(signer: Signer): ExchangePoolAccessControl__factory {
    return super.connect(signer) as ExchangePoolAccessControl__factory
  }
  static readonly bytecode = _bytecode
  static readonly abi = _abi
  static createInterface(): ExchangePoolAccessControlInterface {
    return new utils.Interface(_abi) as ExchangePoolAccessControlInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExchangePoolAccessControl {
    return new Contract(address, _abi, signerOrProvider) as ExchangePoolAccessControl
  }
}
