stages:
  - test
  - build
  - deploy

include:
  - project: '$DEVOPS_PROJECT_PATH'
    ref: 'main'
    file: 'gitlabci/test/backend/lint/.gitlab-ci.yml'
  - project: '$DEVOPS_PROJECT_PATH'
    ref: 'main'
    file: 'gitlabci/test/backend/type/.gitlab-ci.yml'
  - project: '$DEVOPS_PROJECT_PATH'
    ref: 'main'
    file: 'gitlabci/build/backend/.gitlab-ci.yml'
  - project: '$DEVOPS_PROJECT_PATH'
    ref: 'main'
    file: 'gitlabci/deploy/backend/.gitlab-ci.yml'
