/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common'

export interface PrivateSalesInterface extends utils.Interface {
  functions: {
    'buy(uint256)': FunctionFragment
    'coinPrice()': FunctionFragment
    'getContractBalance()': FunctionFragment
    'getContractTokenBalance()': FunctionFragment
    'getVestingWallets(address)': FunctionFragment
    'isAllowed(address)': FunctionFragment
    'owner()': FunctionFragment
    'privateSalesEnabled()': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'setAllowed(address[],bool)': FunctionFragment
    'setPrivateSalesEnabled(bool)': FunctionFragment
    'token()': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'updateCoinPrice(uint256)': FunctionFragment
    'vestingWallets(address,uint256)': FunctionFragment
    'withdraw()': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'buy'
      | 'coinPrice'
      | 'getContractBalance'
      | 'getContractTokenBalance'
      | 'getVestingWallets'
      | 'isAllowed'
      | 'owner'
      | 'privateSalesEnabled'
      | 'renounceOwnership'
      | 'setAllowed'
      | 'setPrivateSalesEnabled'
      | 'token'
      | 'transferOwnership'
      | 'updateCoinPrice'
      | 'vestingWallets'
      | 'withdraw'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'buy',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(functionFragment: 'coinPrice', values?: undefined): string
  encodeFunctionData(functionFragment: 'getContractBalance', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'getContractTokenBalance',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'getVestingWallets',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'isAllowed',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(functionFragment: 'privateSalesEnabled', values?: undefined): string
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'setAllowed',
    values: [PromiseOrValue<string>[], PromiseOrValue<boolean>]
  ): string
  encodeFunctionData(
    functionFragment: 'setPrivateSalesEnabled',
    values: [PromiseOrValue<boolean>]
  ): string
  encodeFunctionData(functionFragment: 'token', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'updateCoinPrice',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'vestingWallets',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string

  decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'coinPrice', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getContractBalance', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getContractTokenBalance',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'getVestingWallets', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isAllowed', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'privateSalesEnabled', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setAllowed', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'setPrivateSalesEnabled',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'updateCoinPrice', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'vestingWallets', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result

  events: {
    'CoinPriceUpdated(uint256)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
    'TokenPurchase(address,uint256,uint256)': EventFragment
    'TokensBought(address,uint256,uint256)': EventFragment
    'Withdrawn(address,uint256)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'CoinPriceUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'TokenPurchase'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'TokensBought'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Withdrawn'): EventFragment
}

export interface CoinPriceUpdatedEventObject {
  newCoinPrice: BigNumber
}
export type CoinPriceUpdatedEvent = TypedEvent<[BigNumber], CoinPriceUpdatedEventObject>

export type CoinPriceUpdatedEventFilter = TypedEventFilter<CoinPriceUpdatedEvent>

export interface OwnershipTransferredEventObject {
  previousOwner: string
  newOwner: string
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>

export interface TokenPurchaseEventObject {
  buyer: string
  amount: BigNumber
  releaseTime: BigNumber
}
export type TokenPurchaseEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TokenPurchaseEventObject
>

export type TokenPurchaseEventFilter = TypedEventFilter<TokenPurchaseEvent>

export interface TokensBoughtEventObject {
  buyer: string
  amount: BigNumber
  price: BigNumber
}
export type TokensBoughtEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TokensBoughtEventObject
>

export type TokensBoughtEventFilter = TypedEventFilter<TokensBoughtEvent>

export interface WithdrawnEventObject {
  owner: string
  amount: BigNumber
}
export type WithdrawnEvent = TypedEvent<[string, BigNumber], WithdrawnEventObject>

export type WithdrawnEventFilter = TypedEventFilter<WithdrawnEvent>

export interface PrivateSales extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: PrivateSalesInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    buy(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    coinPrice(overrides?: CallOverrides): Promise<[BigNumber]>

    getContractBalance(overrides?: CallOverrides): Promise<[BigNumber]>

    getContractTokenBalance(overrides?: CallOverrides): Promise<[BigNumber]>

    getVestingWallets(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>

    isAllowed(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[boolean]>

    owner(overrides?: CallOverrides): Promise<[string]>

    privateSalesEnabled(overrides?: CallOverrides): Promise<[boolean]>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setAllowed(
      addresses: PromiseOrValue<string>[],
      allowed: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setPrivateSalesEnabled(
      enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    token(overrides?: CallOverrides): Promise<[string]>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    updateCoinPrice(
      newCoinPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    vestingWallets(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>
  }

  buy(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  coinPrice(overrides?: CallOverrides): Promise<BigNumber>

  getContractBalance(overrides?: CallOverrides): Promise<BigNumber>

  getContractTokenBalance(overrides?: CallOverrides): Promise<BigNumber>

  getVestingWallets(
    walletAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>

  isAllowed(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>

  owner(overrides?: CallOverrides): Promise<string>

  privateSalesEnabled(overrides?: CallOverrides): Promise<boolean>

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setAllowed(
    addresses: PromiseOrValue<string>[],
    allowed: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setPrivateSalesEnabled(
    enabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  token(overrides?: CallOverrides): Promise<string>

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  updateCoinPrice(
    newCoinPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  vestingWallets(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>

  withdraw(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    buy(amount: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>

    coinPrice(overrides?: CallOverrides): Promise<BigNumber>

    getContractBalance(overrides?: CallOverrides): Promise<BigNumber>

    getContractTokenBalance(overrides?: CallOverrides): Promise<BigNumber>

    getVestingWallets(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>

    isAllowed(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>

    owner(overrides?: CallOverrides): Promise<string>

    privateSalesEnabled(overrides?: CallOverrides): Promise<boolean>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    setAllowed(
      addresses: PromiseOrValue<string>[],
      allowed: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>

    setPrivateSalesEnabled(
      enabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>

    token(overrides?: CallOverrides): Promise<string>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    updateCoinPrice(
      newCoinPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>

    vestingWallets(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>

    withdraw(overrides?: CallOverrides): Promise<void>
  }

  filters: {
    'CoinPriceUpdated(uint256)'(newCoinPrice?: null): CoinPriceUpdatedEventFilter
    CoinPriceUpdated(newCoinPrice?: null): CoinPriceUpdatedEventFilter

    'OwnershipTransferred(address,address)'(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter

    'TokenPurchase(address,uint256,uint256)'(
      buyer?: PromiseOrValue<string> | null,
      amount?: null,
      releaseTime?: null
    ): TokenPurchaseEventFilter
    TokenPurchase(
      buyer?: PromiseOrValue<string> | null,
      amount?: null,
      releaseTime?: null
    ): TokenPurchaseEventFilter

    'TokensBought(address,uint256,uint256)'(
      buyer?: PromiseOrValue<string> | null,
      amount?: null,
      price?: null
    ): TokensBoughtEventFilter
    TokensBought(
      buyer?: PromiseOrValue<string> | null,
      amount?: null,
      price?: null
    ): TokensBoughtEventFilter

    'Withdrawn(address,uint256)'(
      owner?: PromiseOrValue<string> | null,
      amount?: null
    ): WithdrawnEventFilter
    Withdrawn(owner?: PromiseOrValue<string> | null, amount?: null): WithdrawnEventFilter
  }

  estimateGas: {
    buy(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    coinPrice(overrides?: CallOverrides): Promise<BigNumber>

    getContractBalance(overrides?: CallOverrides): Promise<BigNumber>

    getContractTokenBalance(overrides?: CallOverrides): Promise<BigNumber>

    getVestingWallets(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    isAllowed(arg0: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    privateSalesEnabled(overrides?: CallOverrides): Promise<BigNumber>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setAllowed(
      addresses: PromiseOrValue<string>[],
      allowed: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setPrivateSalesEnabled(
      enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    token(overrides?: CallOverrides): Promise<BigNumber>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    updateCoinPrice(
      newCoinPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    vestingWallets(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    buy(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    coinPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getContractBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getContractTokenBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getVestingWallets(
      walletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    isAllowed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    privateSalesEnabled(overrides?: CallOverrides): Promise<PopulatedTransaction>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setAllowed(
      addresses: PromiseOrValue<string>[],
      allowed: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setPrivateSalesEnabled(
      enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    updateCoinPrice(
      newCoinPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    vestingWallets(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>
  }
}
